@echo off
color 0a
title Drax Logger

echo                                                                                                                                                                                                                                                                    
echo                                          :^^^^^^^^:.                                                                                       .^^^^^^^^^:.                                                                                                                                                       =                                  :B@@@@&&&&&##P7:                                                                                  .5&&&@@@@&&&7                                                                                                                                                       
echo                                       .!@@#~:::^~JB@#7      ......    ...           ....          ......    .....                       .:::P@@?:::                ...               ....   .....        ...   .....         ...            ......    ..                                                   
echo                                        ^@@B.      .5@@J    ?&&&&&G:~YG#&#P7.   ~5GB##&&#BP7.     7#&&&&B! .5&&&&&5.                         5@@7              .!YG#&&#BP?^       .75B#&&#GYP&&&&B~   ^JG#&&#BPJB&&&&5.  .~JGB&&&#GY!.     .5&&&&&Y:75B#&B5~                                                
echo                                        ^@@B:       :B@&^   .~~?&@@&@#Y!~Y&&!   ^JY?!~~~~Y@@G:    .^7B@@&?.^G@@&Y~:                          5@@7             7B@&57~~!?G@@P^    ?#@&Y!~~7P@@@@P~^. ^P@@G?~~!JB@@@&7~:  7B@@G?~~~?P@@#7     :~~Y@@&&@BJ!!P@B:                                               
echo                                        ^@@B:       .G@@~      ^#@@5~.    ::       .:^~~^^G@@!        !P@@#&@#J:                             5@@7            ?@@P:       !#@#^  ?@@P:      ~#@@J   :B@&7      .Y@@&:   7@@&7       !#@@?       7@@#J^     :.                                                
echo                                        ^@@B:       :#@&^      ^&@B.            !5#&&&&&&&@@@!         ~B@@@@Y.                              5@@7      !B#7 .B@&^         J@@J  G@@!        Y@@Y   !@@G        ^#@&^   P@@&#&&&&&&&#@@@B.      ?@@Y                                                         
echo                                        ^@@B.      ^P@@?       ^#@B.          .P@@P!:....^B@@~       ~P@@B?5&@#J:                            5@@!      J@@Y  5@@Y.       ^B@&~  J@@5.      ^B@@Y   :B@&!       J@@&^   ?@@#?~~!!!!~~~~!^       7@@Y                                                         
echo                                      .75@@&YJJJJYG@@G~    :?JJ5@@&YJJJJJ~    :B@@J^^^~?5P&@@PJ7..7JG@@@B^  Y@@@&5?^                     !JJJB@@PJJJJJJG@@Y  .J&@#Y!~^~7P@@B!    J&@#J~^~!5&@@@Y    ^G@@P7~^~?B@@@&^    ?#@#Y!^^^^~?YPGJ   ~JJJG@@BJJJJJJ^                                                  
echo                                      :5GGGGGGGGGPY7:      ^PGGGGGGGGGGGG?     .?P#&&&BP?^JGGGBY.:YGGGGG5~ .JPGGGGP7                    .JGGGGGGGGGGGGGGGG7    :75B#&&&#GY~.      :?PB#&&#B5G@@Y      ~YG#&&&#G5&@&^     .75B#&&&&##BPY!   7GGGGGGGGGGGGP~                                                  
echo                                                                                  ..:.                                                                             ..:.               .... .P@&!          ...  !&@P.         ..::..                                                                         
echo                                                                                                                                                                                   ^5GGGGGB&&G~        ?GGGGGG#@#J.                                                                                         
echo                                                                                                                                                                                   :?JJJJJ?!:          ~JJJJJJ7^.                                                                                           
echo                                                                                                                                                                                                                                                                                      

pause >nul
start cmd.exe